/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

/**
 *
 * @author Admin
 */
public class ss extends javax.swing.JPanel {

    /**
     * Creates new form ss
     */
    public ss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "HangSX", "Loại SP", "Size", "Màu Sắc", "TênSP", "Ngày Nhập", "Đơn Giá", "Số Lượng", "Ảnh", "trạng Thái"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
//        // TODO add your handling code here:
//        //showDetail(tblSanPham.getSelectedRow());
//        int row = tblSanPham.getSelectedRow();
//        String MaSP = tblSanPham.getValueAt(row, 0).toString();
//        HangEntity hangSX = (HangEntity)tblSanPham.getValueAt(row, 1);
//        TheLoaiEntity loaiSP = (TheLoaiEntity)tblSanPham.getValueAt(row, 2);
//        SizeEntity size = (SizeEntity)tblSanPham.getValueAt(row, 3);
//        MauSacEntity maMS = (MauSacEntity)tblSanPham.getValueAt(row, 4);
//        String tenSP = tblSanPham.getValueAt(row, 5).toString();
//        String ngayNhap = tblSanPham.getValueAt(row, 6).toString();
//        String donGia = tblSanPham.getValueAt(row, 7).toString();
//        String soLuong = tblSanPham.getValueAt(row, 8).toString();
//        //String anh = tblSanPham.getValueAt(row, 9).toString();
//        Uphinh(tblSanPham.getValueAt(row, 9).toString());
//        //Boolean status = Boolean.parseBoolean(tblSanPham.getValueAt(row, 10).toString());
//        //int status = Integer.parseInt(tblSanPham.getValueAt(row, 10).toString());
//        String status = String.valueOf(tblSanPham.getValueAt(row, 10).toString());
//        if(status.equalsIgnoreCase("Active")){
//            rdoActive.setSelected(true);
//        }else{
//            rdoINActive.setSelected(true);
//        }
//        txtMaSP.setText(MaSP);
//        txtTenSP.setText(tenSP);
//        txtSoluong.setText(soLuong);
//        txtDonGia.setText(donGia);
//        txtNgayNhap.setText(ngayNhap);
//        //radio
//        //        if(status == 0){
//            //            rdoActive.setSelected(true);
//            //        }else{
//            //            rdoINActive.setSelected(true);
//            //        }
//        int tlIndex = findIndexComboboxById(loaiSP.getMaTL());
//        cboTL.setSelectedIndex(tlIndex);
//
//        int hangIndex = findIndexComboHangById(hangSX.getMaHangSX());
//        cboHang.setSelectedIndex(hangIndex);
//
//        int sizeIndex = findIndexComboSizeById(size.getMaSize());
//        cboSize.setSelectedIndex(sizeIndex);
//
//        int msIndex = findIndexComboMSById(maMS.getMaMS());
//        cboMS.setSelectedIndex(msIndex);
//
//        txtMaSP.setEnabled(false);
//        cboHang.setEnabled(false);
//        cboTL.setEnabled(false);
//        txtDonGia.setEnabled(false);
//        txtNgayNhap.setEnabled(false);
    }//GEN-LAST:event_tblSanPhamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
