/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Entities.KhachHang;
import Models.KhachHangModel;
import Utils.XCheck;
import Utils.XDate;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.QLALL;
import services.QLKhachHang;

/**
 *
 * @author HOANGGOANG
 */
public class QLKHForm extends javax.swing.JFrame {
    private final QLALL _qlALL;
    XCheck _check;
    /**
     * Creates new form QLKHForm
     */
    public QLKHForm() {
        initComponents();
        _qlALL = new QLKhachHang();
        _check = new XCheck();
        fillTable(_qlALL.getKhachHang());
        radioGioiTinh();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //List<KhachHang> khachHang = _qlALL.getKhachHang();
    }
    void radioGioiTinh(){
        ButtonGroup btng = new ButtonGroup();
        btng.add(rbn_nu);
        btng.add(rbn_nam);
        rbn_nam.setSelected(true);
    }
    public String maKhachHang(String ten){
        List<KhachHang> lstKH = _qlALL.getKhachHang();
        for(KhachHang x : lstKH){
            if(x.getTenKH().equals(ten)){
                return x.getMaKH();
            }
        }
        return null;
    }
    public String tenKhachHang(String ma){
        List<KhachHang> lstKH = _qlALL.getKhachHang();
        for(KhachHang x : lstKH){
            if(x.getMaKH().equals(ma)){
                return x.getTenKH();
            }
        }
        return null;
    }
    public void fillTable(List<KhachHang> lstKhachHang){
        DefaultTableModel TableModel = new DefaultTableModel();
        TableModel = (DefaultTableModel) tbl_khachHang.getModel();
        TableModel.setRowCount(0);
        int stt = 1;
        for(KhachHang x : lstKhachHang){
            TableModel.addRow(new Object[]{stt++,x.getMaKH(),x.getTenKH(),x.getSDT(),x.isGioiTinh() == true ? "Nam" : "Nữ",x.getDiaChi(),XDate.toString(x.getNgayThamGia(),"dd/MM/yyyy")});
        }
    }
    KhachHangModel getGUI(){
        return new KhachHangModel(txt_maKH.getText(),txt_tenKH.getText(),txt_sdt.getText(),rbn_nam.isSelected()?true:false,txt_diaChi.getText(),date_ngayThamGia.getDate());
    }
    public void showDetail(int index) throws ParseException{
        txt_maKH.setText(tbl_khachHang.getValueAt(index, 1).toString());
        txt_tenKH.setText(tbl_khachHang.getValueAt(index, 2).toString());
        txt_sdt.setText(tbl_khachHang.getValueAt(index, 3).toString());
        rbn_nam.setSelected(tbl_khachHang.getValueAt(index, 4).toString().equals("Nam") ? true : false);
        rbn_nu.setSelected(tbl_khachHang.getValueAt(index, 4).toString().equals("Nữ")? true : false);
        txt_diaChi.setText(tbl_khachHang.getValueAt(index, 5).toString());
        date_ngayThamGia.setDate(XDate.toDate(tbl_khachHang.getValueAt(index, 6).toString(),"MM/dd/yyyy"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_hoaDon = new javax.swing.JButton();
        btn_sanPham = new javax.swing.JButton();
        btn_nhanVien = new javax.swing.JButton();
        btn_khachHang = new javax.swing.JButton();
        btn_thongKe = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();
        btn_dth = new javax.swing.JButton();
        btn_doiMK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        txt_timKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        txt_tenKH = new javax.swing.JTextField();
        rbn_nam = new javax.swing.JRadioButton();
        rbn_nu = new javax.swing.JRadioButton();
        txt_sdt = new javax.swing.JTextField();
        txt_diaChi = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        date_ngayThamGia = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\User.png")); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btn_hoaDon.setBackground(new java.awt.Color(255, 51, 0));
        btn_hoaDon.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\List.png")); // NOI18N
        btn_hoaDon.setText("Hóa đơn");
        btn_hoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoaDonActionPerformed(evt);
            }
        });

        btn_sanPham.setBackground(new java.awt.Color(255, 51, 0));
        btn_sanPham.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Add to basket.png")); // NOI18N
        btn_sanPham.setText("Sản phẩm");

        btn_nhanVien.setBackground(new java.awt.Color(255, 51, 0));
        btn_nhanVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Boy.png")); // NOI18N
        btn_nhanVien.setText("Nhân viên");

        btn_khachHang.setBackground(new java.awt.Color(255, 51, 0));
        btn_khachHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Girl.png")); // NOI18N
        btn_khachHang.setText("Khách hàng");

        btn_thongKe.setBackground(new java.awt.Color(255, 51, 0));
        btn_thongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Bar chart.png")); // NOI18N
        btn_thongKe.setText("Thống kê");

        btn_dangXuat.setBackground(new java.awt.Color(255, 51, 0));
        btn_dangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Exit.png")); // NOI18N
        btn_dangXuat.setText("Đăng xuất");

        btn_dth.setBackground(new java.awt.Color(255, 51, 0));
        btn_dth.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Remove from basket.png")); // NOI18N
        btn_dth.setText("Đổi trả hàng");

        btn_doiMK.setBackground(new java.awt.Color(255, 51, 0));
        btn_doiMK.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Refresh.png")); // NOI18N
        btn_doiMK.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_thongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_doiMK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_dth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_khachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_dangXuat, btn_doiMK, btn_dth, btn_hoaDon, btn_khachHang, btn_nhanVien, btn_sanPham, btn_thongKe});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_hoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sanPham)
                .addGap(26, 26, 26)
                .addComponent(btn_nhanVien)
                .addGap(30, 30, 30)
                .addComponent(btn_khachHang)
                .addGap(28, 28, 28)
                .addComponent(btn_dth)
                .addGap(28, 28, 28)
                .addComponent(btn_thongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_doiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangXuat)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_dangXuat, btn_doiMK, btn_dth, btn_hoaDon, btn_khachHang, btn_nhanVien, btn_sanPham, btn_thongKe});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý khách hàng"));

        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KH", "Họ tên khách hàng", "Số điện thoại", "Giới tính", "Địa chỉ", "Ngày tham gia"
            }
        ));
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachHang);

        jLabel1.setText("Mã khách hàng :");

        jLabel2.setText("Họ tên khách hàng :");

        jLabel3.setText("Giới tính :");

        jLabel4.setText("Số điện thoại :");

        jLabel5.setText("Địa chỉ :");

        jLabel6.setText("Ngày tham gia :");

        rbn_nam.setText("Nam");

        rbn_nu.setText("Nữ");

        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_timKiem)
                        .addGap(32, 32, 32)
                        .addComponent(txt_timKiem))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_sdt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(rbn_nam)
                                .addGap(66, 66, 66)
                                .addComponent(rbn_nu))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tenKH))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_diaChi))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date_ngayThamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btn_sua)
                                .addGap(27, 27, 27)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_sua, btn_them});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timKiem)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(date_ngayThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbn_nam)
                            .addComponent(rbn_nu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sua)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_sua, btn_them});

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("PHẦN MỀM QUẢN LÝ BÁN GIẦY");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOANGGOANG\\Documents\\NetBeansProjects\\QL_DUAN1\\src\\main\\resources\\Icon\\Alarm.png")); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel8)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(83, 83, 83))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if(txt_maKH.getText().isBlank() || txt_tenKH.getText().isBlank() || txt_sdt.getText().isBlank() || txt_diaChi.getText().isBlank() ){
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            return;
        }
        if(!_check.checkSDT(txt_sdt.getText()) || !_check.checkSo(txt_sdt.getText())){
            JOptionPane.showMessageDialog(this,"Số điện thoại phải đúng 10 kí tự là số!");
            return;
        }
        
        int input = JOptionPane.showConfirmDialog(null, "Bạn xác định muốn thêm?", "Selection an Option", JOptionPane.YES_NO_OPTION);
        if(input == 0){
            JOptionPane.showMessageDialog(this, _qlALL.createKH(getGUI()));
            fillTable(_qlALL.getKhachHang());
        }
        
        //JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        if(txt_maKH.getText().isBlank() || txt_tenKH.getText().isBlank() || txt_sdt.getText().isBlank() || txt_diaChi.getText().isBlank() ){
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            return;
        }
        if(!_check.checkSDT(txt_sdt.getText()) || !_check.checkSo(txt_sdt.getText())){
            JOptionPane.showMessageDialog(this,"Số điện thoại phải đúng 10 kí tự là số!");
            return;
        }
        int input = JOptionPane.showConfirmDialog(null, "Bạn xác định muốn sửa?", "Selection an Option", JOptionPane.YES_NO_OPTION);
        if(input == 0){
            JOptionPane.showMessageDialog(this, _qlALL.updateKH(getGUI()));
            fillTable(_qlALL.getKhachHang());
        }
        //JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_maKH.setEnabled(true);
        txt_maKH.setText("");
        txt_tenKH.setText("");
        txt_sdt.setText("");
        rbn_nam.setSelected(true);
        txt_diaChi.setText("");
        txt_timKiem.setText("");
        date_ngayThamGia.setDate(new Date());
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        try {
            // TODO add your handling code here:
            showDetail(tbl_khachHang.getSelectedRow());
            txt_maKH.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(QLKHForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_khachHangMouseClicked

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        if(txt_timKiem.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Không đc để trống");
            return;
        }
        if(!_check.checkSDT(txt_timKiem.getText()) || !_check.checkSo(txt_timKiem.getText())){
            JOptionPane.showMessageDialog(this,"Số điện thoại phải đúng 10 kí tự là số!");
            return;
        }
        int input = Integer.parseInt(String.valueOf(_qlALL.findBySdt(txt_timKiem.getText()).size()));
        if(input == 0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng cần tìm!");
            fillTable(_qlALL.findBySdt(txt_timKiem.getText()));
            return;   
        }
        fillTable(_qlALL.findBySdt(txt_timKiem.getText()));
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_hoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_doiMK;
    private javax.swing.JButton btn_dth;
    private javax.swing.JButton btn_hoaDon;
    private javax.swing.JButton btn_khachHang;
    private javax.swing.JButton btn_nhanVien;
    private javax.swing.JButton btn_sanPham;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thongKe;
    private javax.swing.JButton btn_timKiem;
    private com.toedter.calendar.JDateChooser date_ngayThamGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbn_nam;
    private javax.swing.JRadioButton rbn_nu;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_maKH;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenKH;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
